name: Web Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'dev'
env:
  TAG: ${{ github.event.inputs.tag || 'dev' }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login docker regsitry
      run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}    
    - name: Build the Docker image
      run: docker build . --file web.Dockerfile --tag zlzforever/wildgoose-web:${{ env.TAG }}
    - name: Publish the Docker image
      run: docker push zlzforever/wildgoose-web:${{ env.TAG }}
